name: Test Packages
# This workflow tests the latest (third-party hosted) available builds

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  schedule:
    - cron:  '0 23 * * *'

defaults:
  run:
    shell: bash


jobs:
  cleanup-runs:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test packages') || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  test-wheel:
    needs: cleanup-runs
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test packages') || github.event_name == 'schedule' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package:
          - engine
          - utils
          - perception/activity_recognition
          - perception/compressive_learning
          - perception/face_recognition
          - perception/heart_anomaly_detection
          - perception/multimodal_human_centric
          - perception/object_tracking_2d
          - perception/pose_estimation
          - perception/fall_detection
          - perception/speech_recognition
          - perception/skeleton_based_action_recognition
          - perception/semantic_segmentation
          - perception/object_detection_2d/centernet
          - perception/object_detection_2d/detr
          - perception/object_detection_2d/gem
          - perception/object_detection_2d/ssd
          - perception/object_detection_2d/yolov3
          - perception/object_detection_2d/retinaface
          - perception/object_detection_2d/nms
          - perception/facial_expression_recognition
          # - perception/object_detection_3d
          # - control/mobile_manipulation
          # - simulation/human_model_generation
          # - control/single_demo_grasp
          # - perception/object_tracking_3d
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Wheel
      run: |
        export DISABLE_BCOLZ_AVX2=true
        python -m pip install --upgrade pip
        sudo apt -y install python3.8-venv libfreetype6-dev git build-essential cmake python3-dev wget libopenblas-dev libsndfile1 libboost-dev python3-dev
        python3 -m venv venv
        source venv/bin/activate
        pip install wheel
        pip install opendr-toolkit-engine
        pip install opendr-toolkit
        python -m unittest discover -s tests/sources/tools/${{ matrix.package }}
  test-wheel-separate:
    needs: cleanup-runs
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package:
          - engine
          - utils
          - perception/activity_recognition
          - perception/compressive_learning
          - perception/face_recognition
          - perception/heart_anomaly_detection
          - perception/multimodal_human_centric
          - perception/object_tracking_2d
          - perception/pose_estimation
          - perception/fall_detection
          - perception/speech_recognition
          - perception/skeleton_based_action_recognition
          - perception/semantic_segmentation
          - perception/object_detection_2d/centernet
          - perception/object_detection_2d/detr
          - perception/object_detection_2d/gem
          - perception/object_detection_2d/ssd
          - perception/object_detection_2d/yolov3
          - perception/object_detection_2d/retinaface
          - perception/object_detection_2d/nms
          - perception/facial_expression_recognition
          # - perception/object_detection_3d
          # - control/mobile_manipulation
          # - simulation/human_model_generation
          # - control/single_demo_grasp
          # - perception/object_tracking_3d
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Wheel Separately
      run: |
        export DISABLE_BCOLZ_AVX2=true
        sudo apt -y install python3.8-venv libfreetype6-dev git build-essential cmake python3-dev wget libopenblas-dev libsndfile1 libboost-dev libeigen3-dev
        python3 -m venv venv
        source venv/bin/activate
        pip install wheel
        # Install engine and requirements for other packages
        pip install opendr-toolkit-engine
        # The following two are dependecies for some other packages and pip cannot automatically install them if they are not on a repo
        pip install opendr-toolkit-compressive-learning
        pip install opendr-toolkit-object-detection-2d
        pip install opendr-toolkit-pose-estimation

        # Install specific package for testing
        package=$(sed "s/_/-/g" <<< ${{ matrix.package }})
        arr=(${package//// })
        if [ ! -z ${arr[1]} ]; then
            package=${arr[1]}
        fi
        echo "Installing $package package"
        # Utils contains hyperparameter tuning
        if [ "$package" == "utils" ]; then
              pip install opendr-toolkit-hyperparameter-tuner
        else
              pip install opendr-toolkit-$package
        fi
        python -m unittest discover -s tests/sources/tools/${{ matrix.package }}
  test-docker:
    needs: cleanup-runs
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test packages') || github.event_name == 'schedule' }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package:
          - engine
          - utils
          - perception/activity_recognition
          - perception/compressive_learning
          - perception/face_recognition
          - perception/heart_anomaly_detection
          - perception/multimodal_human_centric
          - perception/object_tracking_2d
          - perception/pose_estimation
          - perception/fall_detection
          - perception/speech_recognition
          - perception/skeleton_based_action_recognition
          - perception/semantic_segmentation
          - perception/object_detection_2d/centernet
          - perception/object_detection_2d/detr
          - perception/object_detection_2d/gem
          - perception/object_detection_2d/ssd
          - perception/object_detection_2d/yolov3
          - perception/object_detection_2d/retinaface
          - perception/object_detection_2d/nms
          - perception/facial_expression_recognition
          - perception/object_detection_3d
          - control/mobile_manipulation
          - simulation/human_model_generation
          - control/single_demo_grasp
          - planning/end_to_end_planning
          # - perception/object_tracking_3d
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 10
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Docker
      run: |
        tag=$(git describe --tags --abbrev=0)
        docker run --name toolkit -i opendr/opendr-toolkit:cpu_${tag} bash
        docker start toolkit
        docker exec -i toolkit bash -c "source bin/activate.sh && source tests/sources/tools/control/mobile_manipulation/run_ros.sh && python -m unittest discover -s tests/sources/tools/${{ matrix.package }}"
